### ISSUE TITLE
Il n'y a pas de licence !

### ISSUE THREAD

**Issue by franc00018** [ClaudeCoulombe/JPPT-0#1]
Il faudrait ajouter une licence pour clarifier les conditions d'utilisation de ce projet.

**Comment by ClaudeCoulombe** [comment]
Oups! Un oubli... C'est corrigé, je propose une licence Apache, version 2.0. Mon seul souci est avec les données. Ce sont de petits jeux de données glanés sur le web. Mais au pire je les retirerai si quelqu'un s'en offusquait. Merci François!
